{
 "title": "air5-eda-uc2-dashb",
 "time": { "from": "2024-12-19T21:00:00.000Z", "to": "2024-12-19T22:59:59.000Z" },
 "panels": [
  {
   "title": "Temperature - Last real time value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc2-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_field\"] == \"temp\") \n|> last()"
    }
   ]
  },
  {
   "title": "Humidity - Last real time value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc2-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_field\"] == \"hum\") \n|> last()\n\n"
    }
   ]
  },
  {
   "title": "Overall measures in time range ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc2-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)"
    }
   ]
  },
  {
   "title": "Temperature - Intensity Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc2-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"temp\")\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}