{
 "title": "air5-eda-uc1-dashb",
 "time": { "from": "2025-11-10T08:47:40.519Z", "to": "2025-11-10T12:12:42.363Z" },
 "panels": [
  {
   "title": "Focus on measures: pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc1-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"deviceId\"] == \"sensor-R\")\n|> filter(fn: (r) => r[\"_field\"] == \"pressure\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n|> yield(name: \"pression_phase_R\")"
    }
   ]
  },
  {
   "title": "Focus on measures: temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc1-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n// Specific filter for sensor R\n|> filter(fn: (r) => r[\"deviceId\"] == \"sensor-R\")\n|> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n|> yield(name: \"temperature_phase_R\")\n"
    }
   ]
  },
  {
   "title": "Measures per operative status in time range",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc1-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_field\"] == \"temperature\") \n|> group(columns: [\"status\"])\n|> count()\n|> yield(name: \"status_count\")"
    }
   ]
  },
  {
   "title": "Overall measures in time range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc1-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)"
    }
   ]
  }
 ]
}