{
 "title": "air5-eda-uc4-dashb",
 "time": { "from": "2025-12-23T16:45:00.000Z", "to": "2025-12-23T17:45:00.000Z" },
 "panels": [
  {
   "title": "Axis Position \"Trailing\"",
   "type": "xychart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc4-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"robot_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pos_deg\")\n  // We pivot so that each axis becomes a column, making it easier for XY Chart\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"axis_id\"], valueColumn: \"_value\")\n  |> yield(name: \"motion_path\")"
    }
   ]
  },
  {
   "title": "Joint Temperature Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc4-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop) \n|> filter(fn: (r) => r[\"_measurement\"] == \"robot_metrics\")\n|> filter(fn: (r) => r[\"_field\"] == \"temp_cel\") \n// Calculate the average temperature for the selected window \n|> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false) \n|> yield(name: \"thermal_load\")"
    }
   ]
  },
  {
   "title": "Multi-Axis Current vs. Vibration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc4-data\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"robot_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_amp\" or r[\"_field\"] == \"vibration_mm_s\")\n  // Keep axis_id to separate the lines in the legend\n  |> yield(name: \"electrical_mechanical_correlation\")"
    }
   ]
  },
  {
   "title": "Overall measures in time range",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"air5-eda-uc4-data\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n"
    }
   ]
  }
 ]
}